spring:
  profiles:
    active: secondLocal
server:
  baseUrl: http://localhost:1000/
  imageUrl: images/
---

spring:
  profiles: local
server:
  baseUrl: http://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/
#spring:
#  profiles: secondLocal
#server:
#  baseUrl: http://s3-ap-southeast-1.amazonaws.com/se331/
#  imageUrl: pics/